http:
  services:
    omeka-s:
      loadBalancer:
        servers:
          - url: "http://omeka-s:80"
  routers:
    omeka-s-web:
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - web
      service: omeka-s
